import { Fragment } from "react";
import Image from "next/image";
import { Card, CardContent, Typography } from "@mui/material";
import Masonry from "@mui/lab/Masonry";
import Avatar from "@mui/material/Avatar";

function StoryList(props) {
  console.log(props);
  const list = props.stories.map((e) => (
    <Card key={e.id}>
      <CardContent sx={{ paddingBottom: 1 }}>
        <Typography variant="h5">{e.title}</Typography>
        {/* Avatar  */}
        <div
          style={{
            display: "grid",
            gridAutoFlow: "column",
            justifyContent: "start",
            alignItems: "center",
            gap: 10,
            paddingTop: 3,
          }}
        >
          <Avatar
            sx={{ width: 24, height: 24 }}
            src={e.user && e.user.photoURL}
          ></Avatar>
          <Typography variant="subtitle1">
            Generated by {e.user ? e.user.displayName : "Anonymous"}
          </Typography>
        </div>
        {/* Avatar */}
      </CardContent>
      {e.img && (
        <Image width={500} height={500} src={e.img} alt={e.alt}></Image>
      )}
      <CardContent>
        <Typography
          sx={{ whiteSpace: "pre-line", marginTop: -7 }}
          variant="body1"
        >
          {e.story}
        </Typography>
      </CardContent>
    </Card>
  ));

  return (
    <Fragment>
      <Typography p={2} variant="h4">
        {props.pageTitle}
      </Typography>
      <Masonry
        defaultHeight={41000}
        defaultColumns={2}
        defaultSpacing={2}
        columns={{ xs: 1, sm: 2, md: 3 }}
        spacing={2}
      >
        {list.map((list, index) => (
          <div key={index} sx={{ list }}>
            {list}
          </div>
        ))}
      </Masonry>
    </Fragment>
  );
}

export default StoryList;
